# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rspec_extensions"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zachary Powell"]
  s.date = "2014-08-22"
  s.email = "zach@babelian.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md"
  ]
  s.homepage = "http://github.com/babelian/rspec_extensions"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Extensions for RSpec"
end

