# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rspec_extensions 1.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rspec_extensions"
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Zachary Powell"]
  s.date = "2014-09-11"
  s.email = "zach@babelian.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "lib/rspec_extensions/alias_spec.rb",
    "lib/rspec_extensions/matchers/have_error.rb",
    "rspec_extensions.gemspec"
  ]
  s.homepage = "http://github.com/babelian/rspec_extensions"
  s.rubygems_version = "2.2.2"
  s.summary = "Extensions for RSpec"
end

